# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout TU-Editor
        uses: actions/checkout@v3
        with:
          path: TU-Editor
      - name: Checkout CodeMirror-NetLogo
        uses: actions/checkout@v3
        with:
          repository: NetLogo-Mobile/CodeMirror-NetLogo
          path: CodeMirror-NetLogo
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install lezer/generator
        run: npm install @lezer/generator --global
      - name: Install rollup
        run: npm install rollup --global
      - name: Build the project for CodeMirror-NetLogo
          run: |
            cd TU-Editor
            npm install
            npm run build
            cd ..
      - name: Build the project for TU-Editor
          run: |
            cd TU-Editor
            npm install
            npm run build
            cd ..
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./TU-Editor/dist
  
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./TU-Editor/dist
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TU-Editor/dist